### PR TITLE
Add octane link to docs navbar menu

### PR DESCRIPTION
**Pull request by davewasmer**
Octane represents a major shift in Ember, and the edition gives us a chance to advertise this change as a chance for folks to reevaluate Ember who may have dismissed it in the past.

Octane is significant enough that it should be displayed prominently - but I cannot find a single mention of the Octane page anywhere on the Ember site. I couldn't remember the URL, so I had to Google `octane site:emberjs.com` to discover it just to make this PR.

### CODE REVIEW

**Comment by jenweber** [comment]
Hi @davewasmer, can we link to `Editions` instead of Octane directly? Right now, the Octane page depends on the information one level higher. Thanks!

**Comment by davewasmer** [comment]
@jenweber thanks for reviewing!

I definitely think linking to Editions is better than the current situation, but I'd like to suggest that we should link to Octane directly (perhaps the link text could say "Octane Edition"?).

I don't think Editions as a concept are widely understood well enough (yet), and most marketing-style materials (blog posts, conference talks, etc) are referring to "Octane". Plus, only having a single edition makes it a little harder to understand the concept.

In other words, I don't think linking directly to Editions matches the mental model or goals of most users.

I imagine most people arrive at the site with the goal of wanting to know more about this "Octane" thing they've heard about, or how to try it out (rather than the goal of perusing Editions or understanding them better conceptually).

With that in mind, I'd suggest we flip the order and link directly to Octane (for now), and that the Octane page should have a "What are Editions?" link.

**Comment by jenweber** [comment]
@davewasmer seems like a good compromise. @MelSumner does that seem ok to you?

**Comment by MelSumner** [comment]
We are not really promoting Octane yet- we have a marketing team spinning up next week, and the new website launch with a target date in the end of June. 

If anything, we should link to the Editions page from the current site (but only that for now).  

The Ember Community should be using this time to preview Octane, and file issues when bugs are found. 

After we declare the edition stable, THEN we should be shouting about it from the rooftops. Having the backup of the marketing and the new website will also very much help this. 

I know it's hard to KNOW that something awesome is coming and not talk about it immediately- but we want to be prudent and invite the rest of the developer community to use a product that doesn't have a lot of gotchas. 

I hope this makes sense- I'm willing to talk more on Discord if that's helpful.

**Comment by davewasmer** [comment]
Hey @MelSumner, thanks for weighing in!

I think I'd disagree with your assessment on whether we should be promoting Octane. I've outlined some reasons below, but before I dive into it, I'm curious to understand what you see as the downside so I make sure I understand your perspective. Is it mostly focused on users potentially having a sub-par experience with Octane if they try things out before we've ironed out remaining kinks, or is there something else?

> We are not really promoting Octane externally yet

I guess I'm a little confused here about what constitutes "promoting externally" here. From what I can see, Octane is already quite public and being promoted:

* The EmberConf opening keynote was almost exclusively focused on Octane
* There was an Ember Conf workshop titled "Modern Ember with Octane", as well as "Intro to Ember Editions & Octane by Robert Jackson"
* Ember Times has mentioned Octane in recent issues multiple times

There's also the general community conversation, which is much harder to quantify, but I would argue certainly includes a healthy amount of discussion around Octane.

> If anything, we should figure out where the Editions page will live in the page hierarchy, and put that in the navbar.

I'd return to my previous points here: even with a fully baked Octane, I'm not sure it makes sense to link to an "Editions" page, which then links to "Octane" - I don't think that's going to line up with visitors' mental models until at least the next edition after Octane.

> The Ember Community should be using this time to preview Octane, and file issues when bugs are found.

Wouldn't making Octane documentation and current status more discoverable help with this?

> After we declare the edition stable, THEN we should be shouting about it from the rooftops- and the backup of the marketing team and new website will also very much help this.

I love the idea of a marketing team and can't wait to see the new site rolled out - but I don't see why we should wait until those things happen to link to Octane.

It seems relatively straightforward to add disclaimers / preview warnings to the Octane page to reinforce that some of this is bleeding edge still?

**Comment by mansona** [comment]
@davewasmer just to clarify a few of your points: 

> The EmberConf opening keynote was almost exclusively focused on Octane

The Keynote announced at the end that the Octane **preview** is available now, and yes a lot was talked about what was coming in octane but that is very different.

> Ember Times has mentioned Octane in recent issues multiple times

This is completely true, and a lot of the mentions that I can remember are around asking for help with the work and the documentation for Octane (which purposely has the word `preview` in its subdomain).

> only having a single edition makes it a little harder to understand the concept

With a new concept it's always going to be difficult to communicate the intent perfectly from day one, so we need to iterate on that. The interesting thing about some of the conversation here is that we actually are missing something, @MelSumner mentioned the "current edition" and the important thing to remember is that the **current edition of Ember is "Classic"** 😂 so in fact there are 2 editions: 

- Classic (which is currently active) 
- Octane (which is the next version and has officially put into the "preview" phase as of EmberConf)

This is something that I think we could definitely capture on the editions page but really that should be something done in another PR or discussed in a new issue (let me know @davewasmer if you would like to create that issue).

As for this PR, can you please update it to link to `Editions` and then we can get it merged and iterate 🎉 💪 

Another thing that might be useful to think about as part of this whole conversation: you need to be reasonably "plugged in" to the community to be watching EmberConf videos (or attending EmberConf or watching the live stream) and there will be a large overlap between these people "in the know" and people who are vaguely aware of what Octane is (right now). 

The last thing that we want during the **preview period** is for people who are not "in the know" (and following daily or weekly commits) to think Octane is ready for production and start building apps using it. When you run the current Octane blueprint it installs the `canary` version of quite a few dependencies and all the same caveats around canary and experimental features currently apply to Octane.

What @MelSumner is saying about `promoting Octane externally` is related to this idea, and as soon as Octane is ready I would be very surprised if the homepage doesn't have a **massive** presence for messages like "try octane now" and "interested in octane, click here" 😂

**Comment by davewasmer** [comment]
> so in fact there are 2 editions

Good point - I think that will definitely help communicate the concept more easily if we have Classic and Octane listed side by side.

> The last thing that we want during the preview period is for people who are not "in the know" (and following daily or weekly commits) to think Octane is ready for production and start building apps using it.

I agree, we definitely need to avoid that. 

I am suggesting that it's possible to do that in other ways. Something as simple as a _giant_ warning on the Octane page that says exactly that. I.e. "Octane is not ready for production, but help us get there by trying it out and filing bugs".

To frame it another way - most likely, only a very small number of EmberConf attendees "follow daily or weekly commits" (I'm not in that number!), yet we all watched an _opening keynote_ that talked for an hour about Octane (yes, "preview", but the cat's out of the bag that Octane exists).

To leave EmberConf hyped about Octane, only to find it completely missing from the website (unless you happen to know the direct link) seems like a pretty poor experience.

> As for this PR, can you please update it to link to Editions

Updated

**Comment by davewasmer** [comment]
@MelSumner moved

**Pull request merged**
