### PR TITLE
using field-guide to document instead of markdown-templates

### PR DESCRIPTION
**Pull request by mansona**
Closes https://github.com/ember-learn/ember-styleguide/pull/180

This PR simplifies the documentation and hosting of the ember-styleguide (for the website redesign branch)

Before this PR we were using an addon called `ember-markdown-templates` that was difficult to use and required you to be careful with how you did documentation.

This PR starts using field-guide that allows us to just write Markdown with code examples that are **self-executing**, which allows for very straight forward documentation and demonstration. 

Let me know if anyone has any questions, I would like to get this PR merged this week so that work can continue on the redesign effort 👍 

**Note for reviewers:** you will see a lot of deletions in this PR, this is not actually removing any documentation. Now that code examples are self-executing you no longer need to duplicate the code in the example directly after code-block, and the deletions you are seeing are just these duplicates being removed because they are no longer necessary.

### CODE REVIEW

**Comment by mansona** [comment]
let me know if anyone has any questions 👍

**Comment by sivakumar-kailasam** [comment]
A lot of components don’t seem to be functioning as expected. eg., on the [footer page](https://deploy-preview-186--ember-styleguide.netlify.com/components/footer) the styles seem to be broken & on the [button page](https://deploy-preview-186--ember-styleguide.netlify.com/components/button) the disabled state doesn't seem to be set. Are these expected/known?

**Comment by mansona** [comment]
@sivakumar-kailasam yes this is known already because they haven't been implemented in the redesign branch yet 👍

**Comment by sivakumar-kailasam** [comment]
Oh, good to know.

Regards,
Siva

**Pull request merged**
