### PR TITLE
Simplify `EsHeaderComponent` implementation.

### PR DESCRIPTION
**Pull request by alexeykostevich**
- Update the component to use Ember Octane API.
- Remove the code for reseting `expanded` on CSS breakpoints for
  a more predictable behaviour and prevention of memory leaks.
- Add `navbar-expanded` class to simplify styles and reduce coupling
  with HTML structure.
- Fix accessibility warnings.
- Add additional tests.

### CODE REVIEW

**Comment by mansona** [comment]
wow thanks for the contribution 🎉 I had a quick glance and it looks mostly ok, although I'm not sure we can use `@tracked` quite yet because of the versions of apps that will be consuming the styleguide 🤔 I'll have to get back to you on that one.

I'm concerned merging this into the `update` branch because I would much prefer to merge this into `master` once `update` is merged and the `website-redesign-rfc` branch is merged. There is a PR that is currently blocking this whole process https://github.com/ember-learn/ember-styleguide/pull/301 but I'm hopeful that we can get it unblocked this week 👍 

I just wanted to let you know that there will be a delay getting this merged but it will likely get merged once that delay is fixed 🎉

**Comment by alexeykostevich** [comment]
Thank you for looking at this and sharing the details, @mansona ! It sound great: there is no rush at all with this PR.

I'm all for getting the `master` branch ready first. Frankly, currently, it takes time for new newcomers to find the right place to start.  #301 will make the repository even more contributor-friendly -- great job!

Please, let me know if any help from my side is needed.

**Comment by alexeykostevich** [comment]
@mansona , I've update the PR target to `master`. Please, let me know if you have any concerns about the PR.

**Comment by mansona** [comment]
@alexeykostevich can you rebase this instead of merging 🤔 the history seems a tiny bit out of whack 

Let me know if you have any questions about the rebase 👍 I'm happy to help if you need it

**Comment by alexeykostevich** [comment]
That's a very good point! I've created another PR (https://github.com/ember-learn/ember-styleguide/pull/319) with a 1-commit history.

**Pull request closed without merging**
