### PR TITLE
[Fix] - Reduce specificity

### LINKED ISSUE #54: Styles: Reduce CSS specificity when possible
## Expected Behavior
Lowest possible specificity for CSS tag selectors in order to apply proper styles

## Actual Behavior
some nested tags/styles that cause unnecessary specificity

## Proposed Solution
Code like this:
```
.es-component {
  li { ...
    a { ...
      img { ...
      }
    }
  }
}
```
should be more like this:
```
.es-component
  li { 
    ... 
  }
  a { 
    ... 
  }
  img { 
    ... 
  }
}
```
With the changes in #53 to using classNames instead of tagNames, styles should not bleed between similar tags (i.e. separate images in the same component). And lower specificity will make overriding styles simpler if needed.

### PR DESCRIPTION
**Pull request by localpcguy**
Fixes #54

### CODE REVIEW

**Comment by amyrlam** [comment]
@localpcguy hey! Sorry this has been open so long, was going through my endless PR "review requests" queue

I reviewed the [whitespace insensitive](https://github.com/ember-learn/ember-styleguide/pull/101/files?w=1) files changed and it looks good. Seems like we still want this merged? Are you on Discord? I'm amyrlam on there.

**Comment by localpcguy** [comment]
The only concern I would have with merging is if the CSS has changed significantly since I did this. I wouldn't want to introduce bugs or visual inconsistencies due to things changing in that time frame. I don't know if I'd have much time to make updates right now, under a pretty tight deadline at my day job at the moment. I've joined Discord (same username, I believe) but haven't been too active lately due to other commitments.

**Comment by amyrlam** [comment]
@localpcguy No worries, all good! I haven't been in this repo much so let me find out on #dev-ember-learning if we should rebase and merge or close.

**Comment by amyrlam** [comment]
Ok, I'll think I'll close this since it's out of date, but leave the issue open (as this repo may be picking up momentum again with some of the website initiatives). Sorry again the PR was open for so long!

**Pull request closed without merging**
