### PR TITLE
Tracking Branch for the Ember Website Redesign RFC

### PR DESCRIPTION
**Pull request by mansona**
This PR has been tracking the work for the Ember Styleguide needed for the [Website Redesign RFC](https://github.com/wifelette/rfcs/blob/master/text/0425-website-redesign.md). This branch has already been released as pre-releases and is in use on the [Ember Website](https://emberjs.com) right now.

As we are moving into the next [phase of the redesign project](https://github.com/orgs/ember-learn/projects/39) it is time to release this work as a stable release 🎉 😱 

This PR is too big to review the code directly, but every change was made using a PR to this branch and each of those PRs were reviewed individually. If you would like to review this PR before we merge it then I would recommend reviewing the **output** by looking at the new documentation: https://deploy-preview-145--ember-styleguide.netlify.app/

After this PR is merged to master I will create a new stable release from the master branch 👍

### CODE REVIEW

**Comment by jenweber** [comment]
See https://github.com/ember-learn/guidemaker-ember-template/pull/30 for work to apply base styles to the Guides

**Comment by jenweber** [comment]
See https://github.com/ember-learn/ember-api-docs/pull/645 for API docs

**Comment by jenweber** [comment]
I would like to advocate for merging this, since it's live. That way, I can point new contributors to the live docs site at its usual URL.

**Comment by mansona** [comment]
@jenweber maybe we should discuss this in a meeting? I guess the main issue I have is that it's not updated to Octane and I wanted to be careful with merging and releasing v4.0 as it would be our public API for a while 🤔 

Maybe we should put together a checklist for getting this merged or something? thoughts?

**Comment by mansona** [comment]
This PR is now ready to be reviewed and merged 🎉 I have updated the description with more context for people and a comment about what should or should not be reviewed 👍 

Feel free to ask me any questions you might have

**Comment by jenweber** [comment]
Since this is already in production, I think we should merge it even if changes are needed. SemVer will help us track the work and do updates. Thanks everyone for your work on this!

**Pull request merged**
