### PR TITLE
[WIP] Feature/es card

### LINKED ISSUE #15: Component: es-card
There are four possible items in this element: 
- an image
- a heading
- some text content
- a button (if used, es-button component)

Other criteria: 
- A border color should be able to be defined
- the border color should be transparent by default (a11y) 
- the image should have a border-radius of 2px if square
- the image should be allowed to be a circle
- the heading should be an h3 by default, but other tagNames should be acceptable to support semantic HTML

### The image: 
The image may be positioned:
- to the left of the text 
- centered on top of the text
- positioned to the right of the text 

### The heading: 
The heading may be positioned 
- above both the text and the image (if the element is horizontal)
- above the image and the text (if vertical) 
- below the image but above the text (if vertical) 
The heading should never be placed below all of the elements at once. 

### the Text: 
may be placed:
- next to the image (either to the left or to the right, depending on the placement of the media image). In this instance, the text should be automatically placed based on placement of the image, the user shouldn't have to place both.
- under the image

Sketch of possible iterations: 
image

### PR DESCRIPTION
**Pull request by dan-ste**
Closes #15

### CODE REVIEW

**Comment by Dan-Ste** [comment]
@MelSumner Can you please review the code?
In the current implementation I cover all card use cases from a ticket. Basically now all components of the card (heading, text, image and button) are inside a card component. To give more control over them we should pass attributes down through card component or use component's block semantic (but we lose all styling in this case). It can be annoying and I'm thinking about adding ember-block-slots addon to give more control to the internal components. What do you think?

**Comment by MelSumner** [comment]
@Dan-Ste this is great- good catch moving all of the styles to the app/styles folder. This will be a good move to prep for theming. 

Please resolve the merge conflict and I'll pull down this branch tonight and take a look. 

Thank you for helping! :+1:

**Comment by Dan-Ste** [comment]
@MelSumner done

**Comment by Dan-Ste** [comment]
@MelSumner Tell me please when you have time and I will resolve conflicts again.

**Comment by MelSumner** [comment]
Thanks Dan- over the next couple of days would work. I don't anticipate any major changes.

**Comment by MelSumner** [comment]
hi @Dan-Ste - would love to ship this. When you get a chance to resolve the conflicts, could you do that please? Thank you!

**Comment by Dan-Ste** [comment]
Sure, i'll do it when i have a chance

**Comment by MelSumner** [comment]
hi @dan-ste just checking in - do you think that you could update this branch so we can get it merged? Thanks for your help! 👍

**Comment by dan-ste** [comment]
Hi @MelSumner. I've resolved all conflicts but now checks are failing and I'm not sure what exactly wrong with them

**Comment by dan-ste** [comment]
Something wrong with styles file structure. Why do we have styles in addon and app folders simultaneously in master? They should be only in the app folders

**Comment by MelSumner** [comment]
I am going to close this for now- if we want to re-open it and continue to work on it, we can.

**Pull request closed without merging**
